### ISSUE TITLE
[enhancement] 将构建工具迁移至Rspack

### ISSUE THREAD

**Issue by crrashh1542** [FurryRbl/Kiwi#1]
因为发现SharpIce的项目是拿Webpack做的打包，所以推荐下基于Rust的Rspack（

顺带一提，虽然`terser-webpack-plugin`没法用，但是他们有性能更佳的`SwcJsMinimizerRspackPlugin`

~~天下苦Webpack久矣！~~

**Comment by SharpIceX** [comment]
谢谢建议，但是目前打算使用.NET 8重写项目，Node.js 调用外部库太折磨了。。。

~~以及我还没习惯 Rust 这个这个黑魔法~~

**Comment by SharpIceX** [comment]
思考了一下还只能留在Node.js（x
Rspack的话只能先继续观望，因为被该太多类似的构建工具坑过了（）
